apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins_casc.yml: |
    jenkins:
      systemMessage: |
        Jenkins configured automatically by Jenkins Configuration as Code Plugin
      clouds:
      - kubernetes:
          containerCap: 10
          containerCapStr: "10"
          jenkinsTunnel: "discovery:50000"
          jenkinsUrl: "http://jenkins:8080"
          maxRequestsPerHost: 32
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: "jenkins"
      authorizationStrategy: unsecured
      numExecutors: 0
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
      remotingSecurity:
        enabled: false
    unclassified:
      location:
        url: "http://jenkins:8080"
    jobs:
      - file: /var/jenkins_home/pipelines/compose-pipeline.dsl
  init-script.sh: |
    #!/bin/bash
    set -ex
    mkdir -p /usr/share/jenkins/ref/plugins
    (
        cd /usr/share/jenkins/ref/plugins
        # repair a potentially broken state
        rm -vrf failed-plugins.txt -- *.lock
    )
    grep -hv ^\$ /var/jenkins_static_config/plugins*.txt | /usr/local/bin/install-plugins.sh
  plugins.txt: |
    ace-editor:1.1
    ansicolor:0.7.2
    apache-httpcomponents-client-4-api:4.5.10-2.0
    authentication-tokens:1.4
    blueocean-autofavorite:1.2.4
    blueocean-bitbucket-pipeline:1.23.2
    blueocean-commons:1.23.2
    blueocean-config:1.23.2
    blueocean-core-js:1.23.2
    blueocean-dashboard:1.23.2
    blueocean-display-url:2.4.0
    blueocean-events:1.23.2
    blueocean-git-pipeline:1.23.2
    blueocean-github-pipeline:1.23.2
    blueocean-i18n:1.23.2
    blueocean-jira:1.23.2
    blueocean-jwt:1.23.2
    blueocean-personalization:1.23.2
    blueocean-pipeline-api-impl:1.23.2
    blueocean-pipeline-editor:1.23.2
    blueocean-pipeline-scm-api:1.23.2
    blueocean-rest-impl:1.23.2
    blueocean-rest:1.23.2
    blueocean-web:1.23.2
    blueocean:1.23.2
    bouncycastle-api:2.18
    branch-api:2.5.9
    build-name-setter:2.1.0
    build-pipeline-plugin:1.5.8
    build-timeout:1.20
    cloudbees-bitbucket-branch-source:2.9.2
    cloudbees-disk-usage-simple:0.10
    cloudbees-folder:6.14
    conditional-buildstep:1.3.6
    configuration-as-code:1.43
    credentials-binding:1.23
    credentials:2.3.12
    display-url-api:2.3.3
    docker-commons:1.17
    docker-java-api:3.1.5.2
    docker-plugin:1.2.0
    docker-workflow:1.24
    durable-task:1.34
    echarts-api:4.8.0-2
    extended-read-permission:3.2
    favorite:2.3.2
    generic-webhook-trigger:1.67
    git-client:3.4.2
    git-server:1.9
    git:4.4.0
    github-api:1.115
    github-branch-source:2.8.3
    github:1.31.0
    greenballs:1.15
    handy-uri-templates-2-api:2.1.8-1.0
    htmlpublisher:1.23
    http_request:1.8.26
    jackson2-api:2.11.2
    javadoc:1.6
    jenkins-design-language:1.23.2
    jira:3.1.1
    job-dsl:1.77
    jquery-detached:1.2.1
    jquery:1.12.4-1
    jquery3-api:3.5.1-1
    jsch:0.1.55.2
    junit:1.32
    kubernetes:1.27.0
    mailer:1.32
    mask-passwords:2.13
    matrix-project:1.17
    maven-plugin:3.7
    mercurial:2.10
    metrics:4.0.2.6
    okhttp-api:3.14.9
    parameterized-trigger:2.37
    permissive-script-security:0.6
    pipeline-build-step:2.13
    pipeline-graph-analysis:1.10
    pipeline-input-step:2.11
    pipeline-milestone-step:1.3.1
    pipeline-model-api:1.7.1
    pipeline-model-definition:1.7.1
    pipeline-model-extensions:1.7.1
    pipeline-stage-step:2.5
    pipeline-stage-tags-metadata:1.7.1
    pipeline-utility-steps:2.6.1
    plain-credentials:1.7
    plugin-util-api:1.2.4
    prometheus:2.0.7
    pubsub-light:1.13
    resource-disposer:0.14
    run-condition:1.3
    scm-api:2.6.3
    script-security:1.74
    snakeyaml-api:1.26.4
    sse-gateway:1.23
    ssh-credentials:1.18.1
    ssh-slaves:1.31.2
    structs:1.20
    timestamper:1.11.5
    token-macro:2.12
    trilead-api:1.0.8
    variant:1.3
    workflow-api:2.40
    workflow-basic-steps:2.20
    workflow-cps-global-lib:2.17
    workflow-cps:2.82
    workflow-durable-task-step:2.35
    workflow-job:2.39
    workflow-multibranch:2.22
    workflow-scm-step:2.11
    workflow-step-api:2.22
    workflow-support:3.5
    ws-cleanup:0.38
